export const ROULETTE_NUMBERS = [
    0, 32, 15, 19, 4, 21, 2, 25, 17, 34, 6, 27, 13, 36, 11, 30, 8, 23, 10,
    5, 24, 16, 33, 1, 20, 14, 31, 9, 22, 18, 29, 7, 28, 12, 35, 3, 26
]

export const RED_NUMBERS = [1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36]

const VOISINS_NUMS = [22, 18, 29, 7, 28, 12, 35, 3, 26, 0, 32, 15, 19, 4, 21, 2, 25]
const TIERS_NUMS = [27, 13, 36, 11, 30, 8, 23, 10, 5, 24, 16, 33]
const ORPHELINS_NUMS = [1, 20, 14, 31, 9, 17, 34, 6]
const ZERO_NUMS = [12, 35, 3, 26, 0, 32, 15]

// --- FORENSIC AUDIT: 0-36 ASYMMETRIC OFFSETS ---
// --- FORENSIC AUDIT: MAXIMIZED CHIP ECONOMY OFFSETS ---
// (Generated by find_best_economy.js to minimize chip usage per number)
export const OFFSETS_0_36 = {
    0: { n: [-4, 2], v: [-9, 7] },
    1: { n: [-6, 0], v: [-9, 7] },
    2: { n: [-6, 0], v: [-9, 7] },
    3: { n: [-2, 4], v: [-9, 7] },
    4: { n: [-4, 2], v: [-9, 7] },
    5: { n: [-5, 1], v: [-9, 7] },
    6: { n: [0, 6], v: [-9, 7] },
    7: { n: [-4, 2], v: [-9, 7] },
    8: { n: [-2, 4], v: [-9, 7] },
    9: { n: [0, 6], v: [-9, 7] },
    10: { n: [-4, 2], v: [-9, 7] },
    11: { n: [0, 6], v: [-9, 7] },
    12: { n: [0, 6], v: [-9, 7] },
    13: { n: [-2, 4], v: [-9, 7] },
    14: { n: [-3, 3], v: [-9, 7] },
    15: { n: [-6, 0], v: [-9, 7] },
    16: { n: [-5, 1], v: [-9, 7] },
    17: { n: [-3, 3], v: [-9, 7] },
    18: { n: [-2, 4], v: [-9, 7] },
    19: { n: [-6, 0], v: [-9, 7] },
    20: { n: [-3, 3], v: [-9, 7] },
    21: { n: [-5, 1], v: [-9, 7] },
    22: { n: [-1, 5], v: [-9, 7] },
    23: { n: [-3, 3], v: [-9, 7] },
    24: { n: [-6, 0], v: [-9, 7] },
    25: { n: [-3, 3], v: [-9, 7] },
    26: { n: [-3, 3], v: [-9, 7] },
    27: { n: [-1, 5], v: [-9, 7] },
    28: { n: [-5, 1], v: [-9, 7] },
    29: { n: [-3, 3], v: [-9, 7] },
    30: { n: [-1, 5], v: [-9, 7] },
    31: { n: [0, 6], v: [-9, 7] },
    32: { n: [-5, 1], v: [-9, 7] },
    33: { n: [-6, 0], v: [-9, 7] },
    34: { n: [0, 6], v: [-9, 7] },
    35: { n: [-1, 5], v: [-9, 7] },
    36: { n: [-3, 3], v: [-9, 7] },
};

export const getBetGroups = (num) => {
    if (num === 0) return ['ZERO']

    const groups = []

    // Simple props
    groups.push(RED_NUMBERS.includes(num) ? 'COLOR_RED' : 'COLOR_BLACK')
    groups.push(num % 2 === 0 ? 'EVEN' : 'ODD')
    groups.push(num <= 18 ? 'LOW_18' : 'HIGH_18')

    // Dozens & Columns
    const dozen = Math.ceil(num / 12)
    groups.push(`DOZEN_${dozen}`)

    const col = (num - 1) % 3 + 1
    groups.push(`COLUMN_${col}`)

    // Calles (Street) - 3 numbers (e.g., 1-3, 4-6)
    const street = Math.ceil(num / 3)
    groups.push(`STREET_${street}`)

    // Lineas (Six Line) - 6 numbers (e.g., 1-6, 7-12)
    const line = Math.ceil(num / 6)
    groups.push(`LINE_${line}`)

    // COMBINATIONS (Deep Analysis)
    // Simple Chance Tags for easy combining
    const t_color = RED_NUMBERS.includes(num) ? 'RED' : 'BLACK'
    const t_evod = num % 2 === 0 ? 'EVEN' : 'ODD'
    const t_lohi = num <= 18 ? 'LOW' : 'HIGH'

    // Triads (The 8 zones)
    groups.push(`COMBO_${t_lohi}_${t_color}_${t_evod}`)

    // Dyads (Pairs)
    groups.push(`PAIR_${t_lohi}_${t_color}`) // e.g. LOW_RED
    groups.push(`PAIR_${t_lohi}_${t_evod}`) // e.g. LOW_ODD
    groups.push(`PAIR_${t_color}_${t_evod}`) // e.g. RED_ODD

    return groups
}

const COLORS = ['RED', 'BLACK']
const EVODS = ['EVEN', 'ODD']
const LOHIS = ['LOW', 'HIGH']

const TRIADS = []
LOHIS.forEach(l => COLORS.forEach(c => EVODS.forEach(e => TRIADS.push(`COMBO_${l}_${c}_${e}`))))

const PAIRS = []
LOHIS.forEach(l => COLORS.forEach(c => PAIRS.push(`PAIR_${l}_${c}`)))
LOHIS.forEach(l => EVODS.forEach(e => PAIRS.push(`PAIR_${l}_${e}`)))
COLORS.forEach(c => EVODS.forEach(e => PAIRS.push(`PAIR_${c}_${e}`)))

export const ALL_BET_IDS = [
    'ZERO',
    'COLOR_RED', 'COLOR_BLACK',
    'EVEN', 'ODD',
    'LOW_18', 'HIGH_18',
    ...[1, 2, 3].map(d => `DOZEN_${d}`),
    ...[1, 2, 3].map(c => `COLUMN_${c}`),
    ...Array.from({ length: 12 }, (_, i) => `STREET_${(i * 3) + 1}`), // FIXED: Streets 1, 4, 7... 34
    ...Array.from({ length: 11 }, (_, i) => `LINE_${(i * 3) + 1}`), // FIXED: Lines 1, 4, 7... 31
    ...TRIADS,
    ...PAIRS,
    ...TRIADS,
    ...PAIRS,
]

// --- BET COMBINATION DEFINITIONS ---

// 1. Splits (Vertical & Horizontal)
export const ALL_SPLITS = []
// Horizontal (e.g., 1-2, 2-3)
for (let r = 1; r <= 36; r += 3) {
    ALL_SPLITS.push({ name: `Medio ${r}-${r + 1}`, numbers: [r, r + 1] })
    ALL_SPLITS.push({ name: `Medio ${r + 1}-${r + 2}`, numbers: [r + 1, r + 2] })
}
// Vertical (e.g., 1-4, 2-5)
for (let n = 1; n <= 33; n++) {
    ALL_SPLITS.push({ name: `Medio ${n}-${n + 3}`, numbers: [n, n + 3] })
}
// Zero Splits
ALL_SPLITS.push({ name: 'Medio 0-1', numbers: [0, 1] })
ALL_SPLITS.push({ name: 'Medio 0-2', numbers: [0, 2] })
ALL_SPLITS.push({ name: 'Medio 0-3', numbers: [0, 3] })

// 2. Streets (Calles - Rows of 3)
export const ALL_STREETS = []
for (let n = 1; n <= 34; n += 3) {
    ALL_STREETS.push({ name: `Calle ${n}-${n + 2}`, numbers: [n, n + 1, n + 2] })
}
// Zero Streets
ALL_STREETS.push({ name: 'Calle 0-1-2', numbers: [0, 1, 2] })
ALL_STREETS.push({ name: 'Calle 0-2-3', numbers: [0, 2, 3] })

// 3. Corners (Cuadros)
export const ALL_CORNERS = []
for (let n = 1; n <= 32; n++) {
    if (n % 3 !== 0) { // Skip right edge
        ALL_CORNERS.push({ name: `Cuadro ${n}-${n + 4}`, numbers: [n, n + 1, n + 3, n + 4] })
    }
}
// Zero Corners (First Four 0-1-2-3) - treated as corner in some variants or basket
ALL_CORNERS.push({ name: 'Canasta 0-1-2-3', numbers: [0, 1, 2, 3] })

// 4. Lines (Lineas - Double Rows)
export const ALL_LINES = []
for (let n = 1; n <= 31; n += 3) {
    ALL_LINES.push({ name: `Linea ${n}-${n + 5}`, numbers: [n, n + 1, n + 2, n + 3, n + 4, n + 5] })
}

export const ALL_WAGERABLE_BET_IDS = Array.from(new Set([
    ...Array.from({ length: 37 }, (_, i) => i.toString()),
    'RED', 'BLACK', 'EVEN', 'ODD', 'LOW', 'HIGH',
    'DOZ1', 'DOZ2', 'DOZ3', 'COL1', 'COL2', 'COL3',
    ...ALL_SPLITS.map(sp => `SPLIT_${[...sp.numbers].sort((a, b) => a - b).join('_')}`),
    ...ALL_STREETS.map(s => {
        const sorted = [...s.numbers].sort((a, b) => a - b)
        return s.numbers.includes(0) ? `TRIO_${sorted.join('_')}` : `STREET_${sorted[0]}`
    }),
    ...ALL_CORNERS.map(c => {
        const sorted = [...c.numbers].sort((a, b) => a - b)
        return c.numbers.includes(0) ? `BASKET_${sorted.join('_')}` : `CORNER_${sorted.join('_')}`
    }),
    ...ALL_LINES.map(l => `LINE_${l.numbers[0]}`),
    'ZERO', 'VOISINS', 'TIERS', 'ORPHELINS',
    ...Array.from({ length: 37 }, (_, i) => `NUCLEO_${i}`),
    ...Array.from({ length: 37 }, (_, i) => `VECINOS_${i}`),
    ...Array.from({ length: 37 }, (_, i) => `HUERFANOS_${i}`),
    ...Array.from({ length: 37 }, (_, i) => `TERCIO_${i}`),
]))

export const getCanonicalBetId = (betId) => {
    if (!betId || typeof betId !== 'string') return betId
    let normalized = betId
    if (normalized.startsWith('DOZEN_')) normalized = 'DOZ' + normalized.slice(6)
    if (normalized.startsWith('COLUMN_')) normalized = 'COL' + normalized.slice(7)
    if (normalized === 'COLOR_RED') normalized = 'RED'
    if (normalized === 'COLOR_BLACK') normalized = 'BLACK'
    if (normalized === 'LOW_18') normalized = 'LOW'
    if (normalized === 'HIGH_18') normalized = 'HIGH'
    if (normalized === 'JEU_ZERO') normalized = 'ZERO'

    const parts = normalized.split('_')
    const type = parts[0]
    if (['SPLIT', 'CORNER', 'TRIO', 'BASKET', 'LINE'].includes(type)) {
        const nums = parts.slice(1).map(Number).sort((a, b) => a - b)
        return `${type}_${nums.join('_')}`
    }
    return normalized
}

export const calculateWinnings = (winningNumber, currentBets) => {
    let totalWinnings = 0
    const winningNumStr = winningNumber.toString()

    // Rules
    const isRed = RED_NUMBERS.includes(winningNumber)
    const isBlack = !isRed && winningNumber !== 0
    const isEven = winningNumber !== 0 && winningNumber % 2 === 0
    const isOdd = winningNumber !== 0 && winningNumber % 2 !== 0
    const isLow = winningNumber >= 1 && winningNumber <= 18
    const isHigh = winningNumber >= 19 && winningNumber <= 36

    const isDoz1 = winningNumber >= 1 && winningNumber <= 12
    const isDoz2 = winningNumber >= 13 && winningNumber <= 24
    const isDoz3 = winningNumber >= 25 && winningNumber <= 36

    const isCol1 = winningNumber !== 0 && winningNumber % 3 === 1
    const isCol2 = winningNumber !== 0 && winningNumber % 3 === 2
    const isCol3 = winningNumber !== 0 && winningNumber % 3 === 0

    Object.entries(currentBets).forEach(([rawId, amount]) => {
        let multiplier = 0
        const betId = getCanonicalBetId(rawId)

        // 0. Parse Complex Bets
        if (betId.startsWith('SPLIT')) {
            const parts = betId.split('_')
            // Validation: Must have valid parts
            if (parts.length === 3 && parts.includes(winningNumStr)) multiplier = 17
        } else if (betId.startsWith('CORNER')) {
            const parts = betId.split('_')
            if (parts.length === 5 && parts.includes(winningNumStr)) multiplier = 8
        } else if (betId.startsWith('STREET')) {
            const parts = betId.split('_')
            const startNum = parseInt(parts[1])
            // Standard Street check: start must be 1, 4, 7...
            if (!isNaN(startNum) && startNum >= 1 && startNum <= 34 && ((startNum - 1) % 3 === 0)) {
                if (winningNumber >= startNum && winningNumber <= startNum + 2) multiplier = 11
            }
        } else if (betId.startsWith('LINE')) {
            const parts = betId.split('_')
            const startNum = parseInt(parts[1])
            if (!isNaN(startNum) && startNum >= 1 && startNum <= 31 && ((startNum - 1) % 3 === 0)) {
                if (winningNumber >= startNum && winningNumber <= startNum + 5) multiplier = 5
            }
        } else if (betId.startsWith('TRIO')) {
            const parts = betId.split('_')
            if (parts.includes(winningNumStr)) multiplier = 11
        } else if (betId.startsWith('BASKET')) {
            const parts = betId.split('_')
            if (parts.includes(winningNumStr)) multiplier = 8
        }

        // 1. Straight Up
        else if (betId === winningNumStr) multiplier = 35

        // ... existing cases ...
        else if (betId === 'RED' && isRed) multiplier = 1
        else if (betId === 'BLACK' && isBlack) multiplier = 1
        else if (betId === 'EVEN' && isEven) multiplier = 1
        else if (betId === 'ODD' && isOdd) multiplier = 1
        else if (betId === 'LOW' && isLow) multiplier = 1
        else if (betId === 'HIGH' && isHigh) multiplier = 1
        else if (betId === 'DOZ1' && isDoz1) multiplier = 2
        else if (betId === 'DOZ2' && isDoz2) multiplier = 2
        else if (betId === 'DOZ3' && isDoz3) multiplier = 2
        else if (betId === 'COL1' && isCol1) multiplier = 2
        else if (betId === 'COL2' && isCol2) multiplier = 2
        else if (betId === 'COL3' && isCol3) multiplier = 2

        // 2. Systems and Call Bets (GLI-Standard Resolution)
        else if (betId === 'VOISINS') {
            if ([0, 2, 3].includes(winningNumber)) multiplier = 11
            else if ([25, 26, 28, 29].includes(winningNumber)) multiplier = 8
            else if ([4, 7, 12, 15, 18, 21, 19, 22, 32, 35].includes(winningNumber)) multiplier = 17
        }
        else if (betId === 'TIERS' || betId.startsWith('TERCIO_') || betId.startsWith('TIERS_')) {
            const covered = getCoveredNumbers({ [rawId]: amount })
            if (covered.includes(winningNumber)) multiplier = 17
        }
        else if (betId === 'ORPHELINS') {
            const covered = getCoveredNumbers({ [rawId]: amount })
            if (covered.includes(winningNumber)) {
                if (winningNumber === 1) multiplier = 35
                else if ([6, 9, 14, 17, 20, 31, 34].includes(winningNumber)) multiplier = 17
            }
        }
        else if (betId.startsWith('HUERFANOS_')) {
            const covered = getCoveredNumbers({ [rawId]: amount })
            if (covered.includes(winningNumber)) multiplier = 35
        }
        else if (betId === 'ZERO' || betId === 'JEU_ZERO') {
            if (winningNumber === 26) multiplier = 35
            else if ([0, 3, 12, 15, 32, 35].includes(winningNumber)) multiplier = 17
        }
        else if (betId.startsWith('NUCLEO_') || betId.startsWith('VECINOS_')) {
            const covered = getCoveredNumbers({ [rawId]: amount })
            if (covered.includes(winningNumber)) multiplier = 35
        }

        if (multiplier > 0) {
            totalWinnings += amount + (amount * multiplier)
        }
    })

    return totalWinnings
}

export const getCoveredNumbers = (currentBets) => {
    const coveredNumbers = new Set()

    Object.keys(currentBets).forEach(rawId => {
        const betId = getCanonicalBetId(rawId)

        // 0. Parse Complex Bets
        if (betId.startsWith('SPLIT')) {
            betId.split('_').slice(1).forEach(n => coveredNumbers.add(parseInt(n)))
        } else if (betId.startsWith('CORNER')) {
            betId.split('_').slice(1).forEach(n => coveredNumbers.add(parseInt(n)))
        } else if (betId.startsWith('STREET')) {
            const start = parseInt(betId.split('_')[1])
            for (let i = 0; i < 3; i++) coveredNumbers.add(start + i)
        } else if (betId.startsWith('LINE')) {
            const start = parseInt(betId.split('_')[1])
            for (let i = 0; i < 6; i++) coveredNumbers.add(start + i)
        } else if (betId.startsWith('TRIO')) { // usually 0-1-2 or 0-2-3
            betId.split('_').slice(1).forEach(n => coveredNumbers.add(parseInt(n)))
        } else if (betId.startsWith('BASKET')) { // 0-1-2-3
            betId.split('_').slice(1).forEach(n => coveredNumbers.add(parseInt(n)))
        }
        else if (betId === 'BATCH') {
            // Batch bets (repeats/doubles) are usually re-expanded into currentBets.
            // If we have 'BATCH' key it implies an error in resolving, but ignoring for coverage safe.
        }

        // 1. Straight Up (0-36)
        else if (!isNaN(betId)) {
            coveredNumbers.add(parseInt(betId))
        }

        // 2. Simple Chances (18 nums)
        else if (['RED', 'BLACK', 'EVEN', 'ODD', 'LOW', 'HIGH'].includes(betId)) {
            for (let i = 1; i <= 36; i++) {
                if (
                    (betId === 'RED' && RED_NUMBERS.includes(i)) ||
                    (betId === 'BLACK' && !RED_NUMBERS.includes(i)) ||
                    (betId === 'EVEN' && i % 2 === 0) ||
                    (betId === 'ODD' && i % 2 !== 0) ||
                    (betId === 'LOW' && i <= 18) ||
                    (betId === 'HIGH' && i >= 19)
                ) coveredNumbers.add(i)
            }
        }

        // 3. Dozens (12 nums)
        else if (['DOZ1', 'DOZ2', 'DOZ3'].includes(betId)) {
            const d = parseInt(betId.slice(3))
            const start = (d - 1) * 12 + 1
            for (let i = 0; i < 12; i++) coveredNumbers.add(start + i)
        }

        // 4. Columns (12 nums)
        else if (['COL1', 'COL2', 'COL3'].includes(betId)) {
            const c = parseInt(betId.slice(3))
            for (let i = 1; i <= 36; i++) {
                if (i % 3 === (c === 3 ? 0 : c)) coveredNumbers.add(i) // Fix mod logic: 3%3=0
            }
        }
        // 5. SYSTEMS & CALL BETS (Unification)
        else if (betId === 'VOISINS') VOISINS_NUMS.forEach(n => coveredNumbers.add(n))
        else if (betId === 'TIERS') TIERS_NUMS.forEach(n => coveredNumbers.add(n))
        else if (betId === 'ORPHELINS') ORPHELINS_NUMS.forEach(n => coveredNumbers.add(n))
        else if (betId === 'ZERO' || betId === 'JEU_ZERO') ZERO_NUMS.forEach(n => coveredNumbers.add(n))

        // Dynamic Systems (NUCLEO_X, VECINOS_X, HUERFANOS_X, TERCIO_X)
        else if (
            betId.startsWith('NUCLEO_') ||
            betId.startsWith('VECINOS_') ||
            betId.startsWith('HUERFANOS_') ||
            betId.startsWith('TERCIO_') ||
            betId.startsWith('TIERS_')
        ) {
            const center = parseInt(betId.split('_')[1])
            if (!isNaN(center)) {
                const centerIdx = ROULETTE_NUMBERS.indexOf(center)
                if (centerIdx !== -1) {
                    const type = betId.split('_')[0]
                    let slices = []
                    if (type === 'NUCLEO') {
                        const def = { start: -3, end: 3 }
                        const start = OFFSETS_0_36[center] ? OFFSETS_0_36[center].n[0] : def.start
                        const end = OFFSETS_0_36[center] ? OFFSETS_0_36[center].n[1] : def.end
                        slices = [[start, end]]
                    } else if (type === 'VECINOS') {
                        const def = { start: -9, end: 7 }
                        const start = OFFSETS_0_36[center] ? OFFSETS_0_36[center].v[0] : def.start
                        const end = OFFSETS_0_36[center] ? OFFSETS_0_36[center].v[1] : def.end
                        slices = [[start, end]]
                    } else if (type === 'TERCIO' || type === 'TIERS') {
                        slices = [[11, 22]]
                    } else if (type === 'HUERFANOS') {
                        slices = [[8, 10], [23, 27]]
                    }

                    slices.forEach(([start, end]) => {
                        for (let i = start; i <= end; i++) {
                            let idx = (centerIdx + i) % 37
                            if (idx < 0) idx += 37
                            coveredNumbers.add(ROULETTE_NUMBERS[idx])
                        }
                    })
                }
            }
        }
    })

    return Array.from(coveredNumbers)
}

export const getBetType = (rawId) => {
    if (!rawId || typeof rawId !== 'string') return 'STRAIGHT'
    const betId = getCanonicalBetId(rawId)
    if (betId.includes('SPLIT')) return 'SPLIT'
    if (betId.includes('CORNER') || betId.includes('BASKET')) return 'CORNER'
    if (betId.includes('STREET') || betId.includes('TRIO')) return 'STREET'
    if (betId.includes('LINE')) return 'LINE'
    if (['DOZ1', 'DOZ2', 'DOZ3', 'COL1', 'COL2', 'COL3'].includes(betId)) return 'DOZEN'
    if (['RED', 'BLACK', 'EVEN', 'ODD', 'LOW', 'HIGH'].includes(betId)) return 'SIMPLE'
    return 'STRAIGHT'
}

export const calculateCoverage = (currentBets) => {
    const covered = getCoveredNumbers(currentBets)
    const count = covered.length
    const percent = (count / 37) * 100
    return percent
}

export const calculateMaxPotentialWin = (currentBets) => {
    if (Object.keys(currentBets).length === 0) return { maxWin: 0, bestNumbers: [] }

    let maxWin = 0
    let bestNumbers = []

    // Check all numbers 0-36
    for (let i = 0; i <= 36; i++) {
        const win = calculateWinnings(i, currentBets)
        if (win > maxWin) {
            maxWin = win
            bestNumbers = [i]
        } else if (win === maxWin && maxWin > 0) {
            bestNumbers.push(i)
        }
    }

    return { maxWin, bestNumbers }
}

/**
 * Optimizes a set of numbers into the minimum number of bets (Lines, Corners, Streets, Splits).
 * This ensures "Chip Economy" (Element 19 requirement).
 */
export const optimizeBets = (targetNums) => {
    if (!targetNums || targetNums.length === 0) return [];

    const targetSet = new Set(targetNums.map(n => parseInt(n)));
    let remaining = new Set(targetNums.map(n => parseInt(n)));
    const finalBetIds = [];

    const getCoverageCount = (betNums) => betNums.filter(n => remaining.has(n)).length;
    const consume = (betNums) => betNums.forEach(n => remaining.delete(n));

    // --- STEP 1: DEFINE ALL POSSIBLE BETS WITH THEIR COSTS ---
    const SIMPLE_COST = 5;
    const NORMAL_COST = 1;

    const chances = [
        { id: 'RED', nums: RED_NUMBERS, cost: SIMPLE_COST },
        { id: 'BLACK', nums: ROULETTE_NUMBERS.filter(n => n !== 0 && !RED_NUMBERS.includes(n)), cost: SIMPLE_COST },
        { id: 'EVEN', nums: ROULETTE_NUMBERS.filter(n => n !== 0 && n % 2 === 0), cost: SIMPLE_COST },
        { id: 'ODD', nums: ROULETTE_NUMBERS.filter(n => n !== 0 && n % 2 !== 0), cost: SIMPLE_COST },
        { id: 'LOW', nums: ROULETTE_NUMBERS.filter(n => n >= 1 && n <= 18), cost: SIMPLE_COST },
        { id: 'HIGH', nums: ROULETTE_NUMBERS.filter(n => n >= 19 && n <= 36), cost: SIMPLE_COST }
    ];

    const groupsOf12 = [
        { id: 'DOZ1', nums: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], cost: SIMPLE_COST },
        { id: 'DOZ2', nums: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], cost: SIMPLE_COST },
        { id: 'DOZ3', nums: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], cost: SIMPLE_COST },
        { id: 'COL1', nums: [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34], cost: SIMPLE_COST },
        { id: 'COL2', nums: [2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35], cost: SIMPLE_COST },
        { id: 'COL3', nums: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36], cost: SIMPLE_COST }
    ];

    const complexCandidates = [
        ...ALL_LINES.map(l => ({ id: `LINE_${l.numbers[0]}_${l.numbers[3]}`, nums: l.numbers, cost: NORMAL_COST })),
        ...ALL_CORNERS.map(c => {
            const sorted = [...c.numbers].sort((a, b) => a - b);
            const id = c.numbers.includes(0) ? `BASKET_${sorted.join('_')}` : `CORNER_${sorted.join('_')}`;
            return { id, nums: c.numbers, cost: NORMAL_COST };
        }),
        ...ALL_STREETS.map(s => {
            const sorted = [...s.numbers].sort((a, b) => a - b);
            const id = s.numbers.includes(0) ? `TRIO_${sorted.join('_')}` : `STREET_${sorted[0]}`;
            return { id, nums: s.numbers, cost: NORMAL_COST };
        }),
        ...ALL_SPLITS.map(sp => ({ id: `SPLIT_${[...sp.numbers].sort((a, b) => a - b).join('_')}`, nums: sp.numbers, cost: NORMAL_COST }))
    ];

    const ALL_CANDIDATES = [...groupsOf12, ...complexCandidates, ...chances];

    // --- STEP 2: GREEDY OPTIMIZATION BASED ON COST EFFICIENCY (Cost / New Nums) ---
    while (remaining.size > 0) {
        let bestBet = null;
        let bestEfficiency = Infinity; // Lower is better (Cost / Covered)

        for (const candidate of ALL_CANDIDATES) {
            // STRICT GEOMETRIC AUDIT: Only allow a bet if 100% of its numbers are within the target range
            // This prevents "bloating" (e.g. using a 6-number Line to cover a single isolated number)
            const isClean = candidate.nums.every(n => targetSet.has(n));
            if (!isClean) continue;

            const count = getCoverageCount(candidate.nums);
            if (count > 0) {
                // Efficiency = Cost of the chip / Numbers it covers that we still need
                const efficiency = candidate.cost / count;

                // TIE BREAKER:
                // 1. Better efficiency (Cost / TargetCovered)
                // 3. If equal, MINIMUM total coverage (nums.length) to avoid collateral disaster
                // 4. If still equal, prefer higher coverage (to consolidate chips)
                if (efficiency < bestEfficiency ||
                    (efficiency === bestEfficiency && candidate.nums.length < (bestBet ? bestBet.nums.length : 99)) ||
                    (efficiency === bestEfficiency && candidate.nums.length === (bestBet ? bestBet.nums.length : 99) && count > (bestBet ? getCoverageCount(bestBet.nums) : 0))) {
                    bestEfficiency = efficiency;
                    bestBet = candidate;
                }
            }
        }

        if (bestBet && bestEfficiency < 1) { // 1 is the cost of a Straight Up pleno
            finalBetIds.push(bestBet.id);
            consume(bestBet.nums);
        } else {
            break;
        }
    }

    // --- STEP 3: PLENOS (Remaining) ---
    remaining.forEach(n => finalBetIds.push(n.toString()));

    return finalBetIds;
}

/**
 * Consolidates current active bets by finding covered numbers and rebuilding
 * the layout with optimized chip placements (minimum cost for same coverage).
 */
export const consolidateActiveBets = (currentBets, chipValue = 1) => {
    if (!currentBets || Object.keys(currentBets).length === 0) return {}

    const coveredNumbers = getCoveredNumbers(currentBets)
    if (coveredNumbers.length === 0) return {}

    const optimizedIds = optimizeBets(coveredNumbers)

    const nextBets = {}
    optimizedIds.forEach(id => {
        nextBets[id] = chipValue
    })
    return nextBets
}
